language: python
python:
  - 2.7
before_install:
  - sudo apt-get update
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install flake8
before_script:
  - flake8 siu_data --count --select=E9,F63,F7,F82 --show-source --statistics
script:
  - python -m pytest -s
deploy:
    provider: pypi
    username: "$PYPI_USER"
    password: "$PYPI_PASSWORD"
    distributions: "sdist bdist_wheel"
    on:
        branch: master
        python: 2.7